### ISSUE TITLE
Dashboard / Appointment 

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#101]
VLCC icon must be left aligned

**Comment by rohitrvayuz** [comment]
![Screenshot_1641340314](https://user-images.githubusercontent.com/78350161/148139510-cc85cdb4-2a18-4b55-9589-2d2bd6ec45d0.png)
![Screenshot_1641340315](https://user-images.githubusercontent.com/78350161/148139516-e1b5b40a-7725-4351-b429-8c54fc0b335d.png)
