### ISSUE TITLE
CORS issue  in the APIs

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#11]
@SoniaManocha  we are facing the CORS issue in te Web, but we are using CORS Chrome extentions to make it work please do look in to this issue as soon as possible , you can find the issue in teh below image
![image](https://user-images.githubusercontent.com/78138350/138247329-b55cd247-002e-457f-aac7-b62550685efc.png)

**Comment by kanishkavayuz** [comment]
@SoniaManocha  @PM-Vallesoft  As The https  issue is resolved and its working fine but the CORS issue is not Resolved, since  we are using CORS extension for integrating APIs, we could not find the  issue in the morning, but this issue is not resolved please do look in to this issue. as soon as possible
@rgnarok

**Comment by rgnarok** [comment]
@kanishkavayuz  move this to the web

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @SoniaManocha  
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/78138350/142380772-b237a385-fb91-43ba-905b-fc26003f6cef.png)
we are getting CORS issue in Mobile app also, the 404  response, when we trigger the https://www.lms.vlccwellness.com/api/ as base url

**Comment by rgnarok** [comment]
@PankajBhutani @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
API is giving Appropriate Response in postman.
