### ISSUE TITLE
Clinic Profile

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#129]
On clinic profile when i scroll up the whole screen goes up but we need to fix that only basic information and serice will scroll up not the tabs

**Comment by Shaktivayuz** [comment]
I stopped floating appbar , plz check it otherwise we need to change complete design of this page

**Comment by rgnarok** [comment]
Not working Please correct this

**Comment by rohitrvayuz** [comment]
Uploading Screen Recording 2022-01-05 at 13.55.19.mov…
