### ISSUE TITLE
Clinic Detail

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#130]
The name on the clinic and the name on the mp pin point on the basic information is different please correct
Also add the distance of the clinic from user location on here too

**Comment by Shaktivayuz** [comment]
![claddress](https://user-images.githubusercontent.com/87964189/147906023-f773b7d8-e520-4869-9043-4288dcdeb670.jpeg)

**Comment by Shaktivayuz** [comment]
but why do you need to calculate distance also. bcoz user can get location n direction just by clicking of direction button

**Comment by rgnarok** [comment]
Done
