### ISSUE TITLE
Expert Notification

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#142]
We need an API for getting Appointment Details using appointment ID @PM-Vallesoft

**Comment by rohitrvayuz** [comment]
@PM-Vallesoft Please look into this. This is working on customer side but not for expert.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Please look into this. This is working on customer side but not for expert.

pls check rbs api and pkg api are different...

**Comment by rgnarok** [comment]
@kanishkavayuz  update in this

**Comment by rohitrvayuz** [comment]
@kanishkavayuz
