### ISSUE TITLE
Need API for saving and retreiving Checkout Data

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#143]
@PM-Vallesoft  As we  have discussed Please do Provide an API for Storing Checkout data and for  Retrieving Data as following

1. the Checkout Saving API Should  have three usual parameters(deviceid,client_mobile,authtoken) and the fourthone  "Checkoutdata" variable which stores the string value, after saving the checkout data, i need to get a **unique number** or id as a response
2. the Checkout Saving API Should  have three usual parameters(deviceid,client_mobile,authtoken) and the fourthone "CheckoutdataID" variable which inputs the **unique number* and as i trigger i need to get the saved Checkoutdata as a response

@rgnarok  @rohitrvayuz

**Comment by PM-Vallesoft** [comment]
As discussed yesterday and with my team  I will suggest that there is option where you can use phone storage of user to store session data as used by many apps in local app storage in the phone(SQLITE).... And session cookies for the web. It will increase app speed and remove API dependency. 

API for every task is not viable option

**Comment by rohitrvayuz** [comment]
@kanishkavayuz Connect with me.

**Comment by kanishkavayuz** [comment]
@rohitrvayuz  we need to save checkout data for booking appointments on  Session storage/Cache/local storage, storing data process works fine in web browsers, Please give Clarity on Storing data over  Session storage/Cache/local storage on InApp  Browser of flutter, 

@rgnarok  @PM-Vallesoft

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @rohitrvayuz  hell give clarity on when hell be integrating  PayU in App

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  ill be storing the data in the Localstorage/session storage for web

**Comment by rgnarok** [comment]
@kanishkavayuz  is this closed? Please update here
