### ISSUE TITLE
Serivce name not coming in App for booked RBS services of TestCenter

### ISSUE THREAD

**Issue by PM-Vallesoft** [VAYUZ-VLCC/vlcc-api-issues#144]
**NOTICE**
For test center service that are tagged as RBS("ServiceType": "RBS",) in service master has been made with following changes:-
**"PriceList": "TESTCENTER",**
Maybe thats why service name were not coming in app due to the fact that earlier only types were not including this new type mentioned above. Make necessary changes in your mappings(this change is only for test center used for test purposes). All live centre and related data remains Unaffected..... and hence in app service name might not be coming as we booked only for test center.

For Ex i booked an rbs service from the app itself and service name(bangalore one) is showing up....
![image](https://user-images.githubusercontent.com/43747392/147748283-fdd0a14a-a246-4a66-a9be-5cdd52639384.png)

@kanishkavayuz @rohitrvayuz @Shaktivayuz @kanishkavayuz @rgnarok @ShikharVayuz @PankajBhutani @SoniaManocha @

**Comment by PM-Vallesoft** [comment]
> For test center service that are tagged as RBS in service master has been made with following changes

**Comment by rgnarok** [comment]
@rohitrvayuz  please update on this

**Comment by rohitrvayuz** [comment]
@PM-Vallesoft  Please connect for this.
