### ISSUE TITLE
Expert appointments 

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#146]
Plz add more appointments n video consultation on Sonia number : - 93127 82089 @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> Plz add more appointments n video consultation on Sonia number : - 93127 82089 @PM-Vallesoft

you make the bookings from the app for both type of appointments from clients no. I will assign it to expert. Just mention done once you do that....

**Comment by rohitrvayuz** [comment]
@Shaktivayuz

**Comment by rohitrvayuz** [comment]
Closing this as Appointment added to Sonia and Kanishka
