### ISSUE TITLE
Iteration in appointment listing and video consultation listing

### ISSUE THREAD

**Issue by ShikharVayuz** [VAYUZ-VLCC/vlcc-api-issues#18]
![image](https://user-images.githubusercontent.com/86296418/139401593-54567f7c-a652-49c7-9b8e-314e3b23d553.png)
@PM-Vallesoft  Could you add a field to fetch the appointment date time in milliseconds .

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft any updates ???

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft any updates ???

@ShikharVayuz basically start time is HRS:Mins:sSec, so what you send us , eg: 10:30:23, we return the same time in your api calling. How to return in milliseconds. It;s basically converting  sec*10^-3, if I am correct, then why not calculate at your end. If there is something else, please tell me.....

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft we require the unix time for the appointment. Calculation for the appointment date can be made but you cant make calculations for the start time. Why cant we get an additional field for appointment time in unix value converted.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft we require the unix time for the appointment. Calculation for the appointment date can be made but you cant make calculations for the start time. Why cant we get an additional field for appointment time in unix value converted.

ok, we will give you timestamp.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft  any updates on by when can we expect to receive the timestamp in rbs_appointment, video consultation appointment, appointment list api.

**Comment by PM-Vallesoft** [comment]
PFA screenshot. filed Name added AppointmentStartDateTime and AppointmentEndDateTime

![image](https://user-images.githubusercontent.com/43747392/140032716-d6f3095e-c79c-4670-b639-130f2fe20d24.png)
