### ISSUE TITLE
Empty fields in appointment listing

### ISSUE THREAD

**Issue by ShikharVayuz** [VAYUZ-VLCC/vlcc-api-issues#19]
{
    "Status": 2000,
    "Message": "Success",
    "AppointmentDetails": [
        {
            "AppointmentId": "72",
            "BookingId": "931340",
            "CenterName": "TEST CENTER 311",
            "CenterCode": "INDLTEST0",
            "ClientId": "CLMC/19/00000155010",
            "BookingNumber": "INDLTEST0PKG/22/000001",
            "AppointmentDate": "2021-11-02",
            "AppointmentStartTime": "11:00:00",
            "AppointmentEndTime": "13:00:00",
            "AppointmentRemark": "test",
            "AppointmentAttDoc": "",
            "AppointmentStatus": "Waiting List",
            "AppointmentType": "General",
            "address_line1": "TEST ADDRESS FOR TEST CENTRE",
            "address_line2": "TEST ADDRESS LINE 2",
            "address_line3": "",
            "area_name": "GK - 2",
            "city_name": "NEW DELHI",
            "state_name": "DELHI - NCR",
            "country_name": "INDIA",
            "phone_number": "000000000",
            "center_map": "",
            "center_latitude": "",
            "center_longitude": "",
            "AppointmentServiceDtl": [
                {
                    "AppointmentServiceId": "49",
                    "ServiceName": "",
                    "ServiceCode": ""
                }
            ]
        }
    ]
}

When we book an appointment via package we are recieving empty field data for service name,code,map,lat

**Comment by PM-Vallesoft** [comment]
working on this issue. currently it's only on test center. packages on other center doesn't have the same.
Also FYI would like to tell that data in RBS Appointment list general will not show service code.

**Comment by PM-Vallesoft** [comment]
> working on this issue. currently it's only on test center. packages on other center doesn't have the same. Also FYI would like to tell that data in RBS Appointment list general will not show service code.

PFA screenshot. Basically Packages allocated to you are for test and doesnot have service code. Hence not coming. It's totally coming on live packages.
![WhatsApp Image 2021-11-03 at 14 12 07](https://user-images.githubusercontent.com/43747392/140032207-8d9711d0-f118-442d-b6a1-beeb312c0fc0.jpeg)

**Comment by ShikharVayuz** [comment]
So @PM-Vallesoft could you add some live packages for us to test the flow or is there any other alternative.

**Comment by PM-Vallesoft** [comment]
Allotted to new numbers asked under thread Addition of packages to new numbers.

![image](https://user-images.githubusercontent.com/43747392/141260239-5e88f8bb-1592-4e81-bec6-3a06bc761104.png)
