### ISSUE TITLE
Center master iterations

### ISSUE THREAD

**Issue by ShikharVayuz** [VAYUZ-VLCC/vlcc-api-issues#21]
@PM-Vallesoft Please update the duplicate area name in the center master

**Comment by SoniaManocha** [comment]
@PM-Vallesoft , Pls send me the Center master data with Area name defined .
Will then correct areas.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft , Pls send me the Center master data with Area name defined . Will then correct areas.

[Active Center List(India).xlsx](https://github.com/VAYUZ-VLCC/vlcc-api-issues/files/7460376/Active.Center.List.India.xlsx)

**Comment by rgnarok** [comment]
@SoniaManocha @PM-Vallesoft  any update here?

**Comment by SoniaManocha** [comment]
Area names have been corrected.

**Comment by rgnarok** [comment]
@ShikharVayuz  please check and confirm on this
