### ISSUE TITLE
Expert Mobile App APIs

### ISSUE THREAD

**Issue by rohitrvayuz** [VAYUZ-VLCC/vlcc-api-issues#24]
We require APIs for the Expert Mobile App.

**Comment by rohitrvayuz** [comment]
@kanishkavayuz We have only Signin API as of today.

**Comment by PM-Vallesoft** [comment]
@PankajBhutani @SoniaManocha 
as discussed in the meeting with @SoniaManocha , once we check test data in E-Diary, if all goes fine it will take 3-4 days for all expert API's.(We will check for data)

**Comment by rgnarok** [comment]
@PankajBhutani  @SoniaManocha  can you share what is the start date and end date of the expert APIs

**Comment by rgnarok** [comment]
@PM-Vallesoft @PankajBhutani  will update by Saturday

**Comment by PM-Vallesoft** [comment]
Mail sent today.

**Comment by rgnarok** [comment]
Expert APIs received over the call

**Comment by rohitrvayuz** [comment]
Please attach the Postman collection here.

Regards,
Rohit Rajput
Product Engineer - Mobile Technologies | VAYUZ Technologies
www.vayuz.com ***@***.*** | Skype: business.vayuz
