### ISSUE TITLE
Cancel appointment 

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#25]
Cancel api giving proper response that appointment  has been cancelled but , It is still showing in Appointment Listing 
@PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
yes it will show with status changed as cancelled.

**Comment by Shaktivayuz** [comment]
How the user know , the appointment has been cancelled.If  It is  still visible on screen @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
Please marked appropriate actions on listed appointments based on status.
