### ISSUE TITLE
Empty  field data in Centermaster

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#26]
need to look the empty fields in centermaster 
![image](https://user-images.githubusercontent.com/78138350/140735699-44f5eaf3-1122-4a56-8046-b39cb6661a1e.png)

**Comment by ShikharVayuz** [comment]
@SoniaManocha will check for the same.

**Comment by rgnarok** [comment]
@SoniaManocha, please update

**Comment by SoniaManocha** [comment]
Center Master Empty fields are updated.
