### ISSUE TITLE
Consultation API required

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#29]
Need an API to store the token added from the enable x

**Comment by PM-Vallesoft** [comment]
Sent you an email with updated API collection.
@ShikharVayuz Basically this api has a field as in attachment. You generate token , pass in it and same will be sent as a response to you in Video consulation APi -Client Video Consultations Appointment List
![image](https://user-images.githubusercontent.com/43747392/141296617-a2cc541d-9c10-4ca7-b3f5-dd43165ecf4e.png)

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft will test and revert you back.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft Couldn't we get that appointment token in rbs general appointment list because we have integrated rbs general list rather going with the integration of 2 seperate api's.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Couldn't we get that appointment token in rbs general appointment list because we have integrated rbs general list rather going with the integration of 2 seperate api's.

Enablex works on for video consultations only so use Client Video Consultations Appointment List api only since its for Video consultation only.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft Actually we will handle that in front end and allow the user to join room only if its a video consultation else the user will have no option to join. Here my point was there are many other things linked to rbs general list. So you can just add a field for consultation_token in rbs general and room id will then only be available for the video consultation that i will make sure.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Actually we will handle that in front end and allow the user to join room only if its a video consultation else the user will have no option to join. Here my point was there are many other things linked to rbs general list. So you can just add a field for consultation_token in rbs general and room id will then only be available for the video consultation that i will make sure.

@ShikharVayuz **rbs general** is just a lead for Vlcc and **general appointment list** is actual for user having packages allocated by VLCC.

@SoniaManocha please guide.

**Comment by SoniaManocha** [comment]
EnableX token field is available in both Package and RBS Appointment API. Hope this Clarifies.

**Comment by PM-Vallesoft** [comment]
@ShikharVayuz new mail sent with new api(Video Consultation Token Update RBS) to add token and room in RBS appointment list.
PFA screenshot
![image](https://user-images.githubusercontent.com/43747392/141610859-57bea71b-94ea-4e93-82d1-cb0ed0596f58.png)
