### ISSUE TITLE
Clinic Distance Filter by lat long 

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#30]
@PM-Vallesoft  we are calculating the distance between the current location of the customer and the Clinic using an algorithm but it calculates the distance in a straight line but we need the actual distance. let me know how can we sort this out

**Comment by ShikharVayuz** [comment]
@SoniaManocha will have a discussion with support and update by the End of day.

**Comment by SoniaManocha** [comment]
As the credits are now available in Google account, hope Vayuz team can use Google APIs to calculate the distance between two locations. Pls discuss, if still we have an issue.

**Comment by kanishkavayuz** [comment]
@SoniaManocha  mam we are still getting this issue
![image](https://user-images.githubusercontent.com/78138350/141607427-f04147b9-3cd6-4bd5-868d-ff399771dc50.png)

**Comment by SoniaManocha** [comment]
In case team is not able to use Google API for calculating exact distance between two locations, then pls do not map this functionality in the App. Pls close this point.
