### ISSUE TITLE
Clinic Image Problem 

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#32]
@PM-Vallesoft  We are not able to render the image from this URL https://lms.vlccwellness.com/api/DSC_8517.JPG
@rgnarok

**Comment by PM-Vallesoft** [comment]
Please check with other image you have and let me know if you still require another image.

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  All the centers has this  https://lms.vlccwellness.com/api/DSC_8517.JPG  image,  but its not rendering  because its extension is missing, please resolve this., we need 512x512 dimension

**Comment by SoniaManocha** [comment]
Pls find the Clinic image-
![Clinic Image2](https://user-images.githubusercontent.com/92796732/141609712-f1848400-81fe-4510-acca-01ce0f4cc7a4.jpg)

**Comment by rgnarok** [comment]
@Shaktivayuz  @ShikharVayuz  do the needful here

**Comment by kanishkavayuz** [comment]
@SoniaManocha   ok well integrate this clinic image
