### ISSUE TITLE
Appointment List API missing parameters 

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#34]
When we book appointment we can write problem description and can also upload attachments. But we are not getting the same in Appointment Listing API , Since I added hard coded problem description and attachment.
![desc](https://user-images.githubusercontent.com/87964189/140917569-be2adeef-2803-4522-8359-c468b41148e9.jpeg)

**Comment by rgnarok** [comment]
@PankajBhutani @SoniaManocha @PM-Vallesoft  any update?

**Comment by PM-Vallesoft** [comment]
> @PankajBhutani @SoniaManocha @PM-Vallesoft any update?
(AppointmentRemark) is the description you want and attachment doc(AppointmentAttDoc)

![image](https://user-images.githubusercontent.com/43747392/141259875-87956b6a-6571-416d-a4c5-4541eb995469.png)

**Comment by Shaktivayuz** [comment]
There is issue  in RBS general appointment list API.We are using the same for cancel n reshedule

**Comment by PM-Vallesoft** [comment]
> There is issue in RBS general appointment list API. We are using the same for cancel n reshedule @PM-Vallesoft

@ShikharVayuz Please try and understand, Cancel and reschedule doesn't work for RBS services. 
the flow is- If user has existing package allocated to them by VLCC it can be booked, cancelled and rescheduled. 
if User goes with RBS appointment, then it's just a lead for VLCC to whom they contact and user avail service. Packages allocated to this user or not is different story altogether.

@SoniaManocha please guide.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft @SoniaManocha @PankajBhutani 

1.  Please try to understand we can have only one option to go with (Rbs General appointment list) or (General appointment list and Video Appointment list).
2. If we integrate (Rbs appointment list) then we are not able to cancel/reschedule appointments or book via package.
3. If we integrate (Video consultations api and general appointment list) then we are able to cancel/reschulde and book via package. But then we will not be able to view bookings made via cash unless they are not approved.
4. Please get this issue resolved already we can go with one option only. We already have invested alot of our time to change to RBS general list api from those two seperate api for general and video consultations.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft @SoniaManocha @PankajBhutani  Any updates on the query.

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft ??

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft ??

@SoniaManocha please takeover

**Comment by SoniaManocha** [comment]
Shikhar, You need to consider Package and RBS appointment API as shared by Aakash.

Both these API have field "Appointment Type" that will have Value as - General(Non-Video appointments) and Video(Video Appointments)

Video Consultation API would not be used.

Hope this Clarifies.

**Comment by ShikharVayuz** [comment]
@SoniaManocha Yes currently it is configured that way only but the problem with this is in RBS appointment list we can not cancel the appointment or rather bookings made via package will not show up in RBS. Please correct me if I am wrong @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> @SoniaManocha Yes currently it is configured that way only but the problem with this is in RBS appointment list we can not cancel the appointment or rather bookings made via package will not show up in RBS. Please correct me if I am wrong @PM-Vallesoft

yes,you are right

**Comment by ShikharVayuz** [comment]
> @PM-Vallesoft @SoniaManocha @PankajBhutani
> 
> 1. Please try to understand we can have only one option to go with (Rbs General appointment list) or (General appointment list and Video Appointment list).
> 2. If we integrate (Rbs appointment list) then we are not able to cancel/reschedule appointments or book via package.
> 3. If we integrate (Video consultations api and general appointment list) then we are able to cancel/reschulde and book via package. But then we will not be able to view bookings made via cash unless they are not approved.
> 4. Please get this issue resolved already we can go with one option only. We already have invested alot of our time to change to RBS general list api from those two seperate api for general and video consultations.

@SoniaManocha So this was only my concern with going on RBS approach.

**Comment by rgnarok** [comment]
@SoniaManocha  @PM-Vallesoft  please help us out here

**Comment by rgnarok** [comment]
@PM-Vallesoft  by when can we expect the cancel reschedule changes in both the apis so that we can take it forward?

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft by when can we expect the cancel reschedule changes in both the apis so that we can take it forward?

Cancel/reschedule for RBS will be provided by tomorrow.

**Comment by PM-Vallesoft** [comment]
> > @PM-Vallesoft by when can we expect the cancel reschedule changes in both the apis so that we can take it forward?
> 
> Cancel/reschedule for RBS will be provided by tomorrow.

Separate API for booth cancel/reschedule sent for RBS in updated collection. Check Mail.

@PankajBhutani @rgnarok @ShikharVayuz @kanishkavayuz

**Comment by ShikharVayuz** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/86296418/143175555-09e42f16-23d9-456e-bbe7-34bf66ae9e51.png">
Endpoint api : http://lms.vlccwellness.com/api/api_client_appointment_list.php?request=client_appointment_list
The Client general appointment list is coming out to be empty. Even if we make a new booking via the package apart from that the previous data was also not visible in the api.
@PM-Vallesoft The api were working fine before 12 pm (23-11-2021)

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft Please look into the issue

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft any updates??

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft any updates??

already on it

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft Updates?

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Updates?
Please check now.
![image](https://user-images.githubusercontent.com/43747392/143395324-79be0ed6-4734-4e1a-a186-043d0899e320.png)
