### ISSUE TITLE
Need Clarity on Appointment Feedback implementation

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#35]
We need clarity on  Appointment Feedback for implementation for both Mobile and Web
@PM-Vallesoft  

@rgnarok

**Comment by PM-Vallesoft** [comment]
Api already provided. its has fields marked with mandatory and optional. Please check.
https://lms.vlccwellness.com/api/api_client_feedback.php?request=api_client_feedback
