### ISSUE TITLE
Need Clarity on Adding Banner in the Clinic Profile

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#36]
As we  have banner in the Clinic Profile Details, we need clarity on the image @PM-Vallesoft  
![image](https://user-images.githubusercontent.com/78138350/141158055-8abae58b-58b3-47c6-970b-7dceaa73c8f1.png)

**Comment by ShikharVayuz** [comment]
We will have a static image in the banner.

**Comment by ShikharVayuz** [comment]
> We will have a static image in the banner.

@PM-Vallesoft @SoniaManocha   we will update you with the dimensions of the banner image required for web and mobile app.

**Comment by rgnarok** [comment]
@ShikharVayuz  @kanishkavayuz update the dimenions
