### ISSUE TITLE
Need Clarity on the package tags

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#37]
As we have tags in the  packages UI, we need clarity on that and neeed corresponding data in the subscribed packages @PM-Vallesoft 
![image](https://user-images.githubusercontent.com/78138350/141158616-b59925e5-2649-4ef0-ad7f-ec99c16aab34.png)

**Comment by ShikharVayuz** [comment]
@PM-Vallesoft update the package listing api and add a field name extensiondays/ extensionMonths regarding to which we will  be showing extensions at frontend.

**Comment by kanishkavayuz** [comment]
@ShikharVayuz  please check the above comments

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft update the package listing api and add a field name extensiondays/ extensionMonths regarding to which we will be showing extensions at frontend.

We don't store two dates that is old date and new date after breakup ,hence cannot add extensiondays/ extensionMonths fields. besides we store and send new updated date as a response in Package listing API.
For tagging we have added a field (value of 0-no breakup,1-made a breakup). PFA screenshot.

![image](https://user-images.githubusercontent.com/43747392/141296204-7b76de4b-6cee-4b8c-8263-25c2045bde0f.png)
