### ISSUE TITLE
Book Appointemnt - Appointment attachment doc is not getting saved

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#38]
@PM-Vallesoft   Appointment attachment doc is not getting saved while making appointment
![image](https://user-images.githubusercontent.com/78138350/141160973-4073a88a-b68c-431e-ba97-c572586c94ae.png)
![image](https://user-images.githubusercontent.com/78138350/141161031-dd646839-f8ce-40d8-b630-cafc7172d49a.png)

**Comment by PM-Vallesoft** [comment]
Appointment booking with attached doc-
![image](https://user-images.githubusercontent.com/43747392/141253933-58dc09cc-0458-4e55-af53-d045cb3ed2c5.png)

Doc in response.
![image](https://user-images.githubusercontent.com/43747392/141259563-f0ff8436-7fad-4b87-9efb-790f98e7e218.png)
