### ISSUE TITLE
Appointments made via the package

### ISSUE THREAD

**Issue by ShikharVayuz** [VAYUZ-VLCC/vlcc-api-issues#39]
@PM-Vallesoft Appointments made via the package are not visible in general_rbs_appointment_list.

**Comment by PM-Vallesoft** [comment]
Please clear this
RBS is not for packages, its adhoc basis like you want service and get it starightaway.
Packages that we have given to you, their appointment will show up in General appointment list and not in rbs. 

Appointment made via rbs appointment booking will only shownin rbs appointment list api.

I have addressed this issue in many comments today.
