### ISSUE TITLE
Https Issue in the Overall Issue

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#4]
Need Secured Integratable HTTPS  Secured API URLs

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft we can disable the https in Postman, we can make it work but the real Problem while integrating the https API , please do check with  SSL Cerification of teh URL

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft we can disable the https in Postman, we can make it work but the real Problem while integrating the https API , please do check with SSL Cerification of teh URL

Issue Resolved.

![image](https://user-images.githubusercontent.com/43747392/139631800-e04983c7-6c19-492e-b0ab-bb7a3dab4a8a.png)

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  ok ill check it.

**Comment by PM-Vallesoft** [comment]
@PankajBhutani @SoniaManocha @rgnarok 
After discussion with Pradeep Sir and Rajesh ji(VLCC)
We have made certain changes and now you can hit api's by adding www before each api URL and get secured resposnes.

![image](https://user-images.githubusercontent.com/43747392/141613934-12d96973-2797-47da-ae34-1dbd44540e47.png)

**Comment by rgnarok** [comment]
@kanishkavayuz  please check and close

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  the URL is working properly now
