### ISSUE TITLE
Need Clarity on the Service Selection in the API 

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#40]
![image](https://user-images.githubusercontent.com/78138350/142359127-619cdb95-2050-4a47-9ef5-3ad84f6c09ab.png)
As we are trying to book appointment using existing customer packages with center code , booking id, bookingitemid but we are confused with services that the packages have  if we need to book app for particular service then we need updation of the api with service code if not we can integrate existeing one, without the service code.
@PM-Vallesoft  @SoniaManocha 

@rgnarok

**Comment by PM-Vallesoft** [comment]
> ![image](https://user-images.githubusercontent.com/78138350/142359127-619cdb95-2050-4a47-9ef5-3ad84f6c09ab.png) As we are trying to book appointment using existing customer packages with center code , booking id, bookingitemid but we are confused with services that the packages have if we need to book app for particular service then we need updation of the api with service code if not we can integrate existeing one, without the service code. @PM-Vallesoft @SoniaManocha
> 
> @rgnarok

couldn't get your point.

**Comment by kanishkavayuz** [comment]
Right, but 
![image](https://user-images.githubusercontent.com/78138350/142377685-1610668c-61de-4523-a581-2d1ec9c8562c.png)
Do we need to choose the particular service of a package for creating appointement   or do we need to book whole package for appointemnt, because this issue raised because theres is a usage left indicator in the services of athe package.

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft

Yes you need to just book for the service and each service has qty as well

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft Im  not getting you

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Im not getting you

Service left qty will keep on changing as you keep on boking particular service for a package while others no booked will not.
What's point you trying to make here?
