### ISSUE TITLE
CORS issue in the API 

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#42]
@PM-Vallesoft @ShikharVayuz @Shaktivayuz 
As we have  intimated the CORS issue that  we are experiencing still has not been resolved and the web and  the mobile app both are experiencing this API, Please don't close this Issue, until the issue  resolved
Web CORS issue
![image](https://user-images.githubusercontent.com/78138350/143183261-606bb2dd-98cc-4974-84e2-f8458b96c23f.png)

Mobile CORS issue
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/78138350/143184164-29b3c297-2cf3-4f9b-a0f5-7ab9e76d92a7.png)

@rgnarok

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  we are using the CORS extension to integrate and test the apis in the web and in Web and we are still using http://lms.vlccwellness.com/api/ baseurl in the mobile app, please resolve this  issue as soon as possible

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  updated image
![image](https://user-images.githubusercontent.com/78138350/143401612-24e2c29a-f9a9-428d-b300-81cf4b9de971.png)

**Comment by rgnarok** [comment]
@PM-Vallesoft please check and update

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @PankajBhutani  @SoniaManocha  Guys Any Updates?...

@rgnarok

**Comment by kanishkavayuz** [comment]
@rgnarok @PM-Vallesoft @SoniaManocha  @PankajBhutani   Shifted to web-API-issue-tracker, Please accept the Web API issue Tracker
