### ISSUE TITLE
Register given Expert Creds 

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#43]
@PM-Vallesoft 
1. As we are testing and integrating expert APIs, Please Register  these numbers in the expert database, the numbers are
8951900164,9717393656

Please Send the profile details of the expert which should have employee code in it, to test the other provided APIs with employee_code

**Comment by kanishkavayuz** [comment]
@rgnarok

**Comment by PM-Vallesoft** [comment]
8951900164-
![image](https://user-images.githubusercontent.com/43747392/143438255-7767c0cc-eb23-4163-9445-17f18226b817.png)

9717393656-
![image](https://user-images.githubusercontent.com/43747392/143438776-fb1ce4a7-8616-4deb-9544-34c33699955b.png)
