### ISSUE TITLE
URL launch isse in RBS Appointment API

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#47]
I m using the URL  http://lms.vlccwellness.com/api/api_client_rbs_appointment_list.php?request=client_rbs_appointment_list. 
Whatever document uploaded by the customer Im unable to open it with that URL link. plz check at you side
![res](https://user-images.githubusercontent.com/87964189/143993691-a0fe7d9d-572e-453e-be92-6733f93ce788.png)
![link](https://user-images.githubusercontent.com/87964189/143993723-ec8e6c9c-c15b-4456-9e85-bf99c61ea9a6.png)

**Comment by PM-Vallesoft** [comment]
> I m using the URL http://lms.vlccwellness.com/api/api_client_rbs_appointment_list.php?request=client_rbs_appointment_list. Whatever document uploaded by the customer Im unable to open it with that URL link. plz check at you side ![res](https://user-images.githubusercontent.com/87964189/143993691-a0fe7d9d-572e-453e-be92-6733f93ce788.png) ![link](https://user-images.githubusercontent.com/87964189/143993723-ec8e6c9c-c15b-4456-9e85-bf99c61ea9a6.png)

Resolved.(API)
![image](https://user-images.githubusercontent.com/43747392/144019412-476ed799-ab6b-4ada-9b8a-9b4dd584b64a.png)

Uploaded image(URL)
![image](https://user-images.githubusercontent.com/43747392/144019606-d71f02aa-aacb-4fa5-88b9-dab8cdce3dfa.png)
