### ISSUE TITLE
Billing Issue

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#48]
@PM-Vallesoft  @SoniaManocha  Guys I have Created a Fresh API key today morning, but the Billing issue is not getting resolved, in the maps for javascript, distance matrix and GeocodingAPI 
![image](https://user-images.githubusercontent.com/78138350/143995282-e35f9ae4-3185-439d-8d3d-9c282c1cee74.png)

**Comment by kanishkavayuz** [comment]
@rgnarok

**Comment by SoniaManocha** [comment]
Pls re-check... Billing is enabled.

**Comment by kanishkavayuz** [comment]
@SoniaManocha mam still same issue

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @rgnarok @SoniaManocha  Ticket has been raised on the Billing Issue, ill update here as soon as I get a response from them.

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @SoniaManocha  The Ticket ID :- 36659209

**Comment by kanishkavayuz** [comment]
@SoniaManocha @PM-Vallesoft   we have shared below concern  on this issue
![image](https://user-images.githubusercontent.com/78138350/144564020-05a19888-b042-4efc-bd63-66bde152b4bb.png)

**Comment by rgnarok** [comment]
waiting for the GCP response

**Comment by rgnarok** [comment]
@kanishkavayuz  move it to web issue tracker
