### ISSUE TITLE
Need payment Gateway API for payments of appointment

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#49]

**Comment by PM-Vallesoft** [comment]
@SoniaManocha @PankajBhutani 
Payment gateway-We have PHP sdk for Payu that will.not work in app. Ask Payu for app sdk. As far as key is concerned i will provide if needed.

**Comment by SoniaManocha** [comment]
Payment Gateway API details were already shared with Vayuz team on 14th Oct.
Screen shot of the same is attached here again for reference
[Screen shot.docx](https://github.com/VAYUZ-VLCC/vlcc-api-issues/files/7633937/Screen.shot.docx)
.

**Comment by rgnarok** [comment]
@PankajBhutani  will update on the payment gateway
