### ISSUE TITLE
Need Reminder APIs

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#50]
@PM-Vallesoft   we need APIs for Reminder as we cannot use local storage in Web, let me know when can we get those APIs(Add, Edit, Update, Delete)

@rgnarok

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft we need APIs for Reminder as we cannot use local storage in Web, let me know when can we get those APIs(Add, Edit, Update, Delete)
> 
> @rgnarok

This is Web development related task. As discussed with @PankajBhutani please close it from here and raise in Web tracker.

**Comment by PankajBhutani** [comment]
@kanishkavayuz Please close this issue as it is related to web,. Please raise this in web issue tracker

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  Please Accept the VLCC-Web-API issues tracker Invite

**Comment by rgnarok** [comment]
No need of Reminder in web confirmed by Team VLCC @kanishkavayuz
