### ISSUE TITLE
Profile API expert

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#51]
We need profile API for expert App as we are not getting employee ID.
Also we are not getting employee ID at login time as we discussed on showcase call.
@PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> We need profile API for expert App as we are not getting employee ID. Also we are not getting employee ID at login time as we discussed on showcase call. @PM-Vallesoft

Already sent over mail few days back , the Expert profile api. check internally. @rgnarok

**Comment by rgnarok** [comment]
Done closing it
