### ISSUE TITLE
staff gender expert

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#52]
Staff Gender should not be null , DOB also should be proper @PM-Vallesoft 
{
    "Status": 2000,
    "Message": "Success",
    "StaffDetails": {
        "StaffInfoId": "16402",
        "Staffname": "Shikar Jain",
        "Staffcode": "TEMP01",
        "CenterName": "TEST CENTER 311",
        "CenterCode": "INDLTEST0",
        "StaffGender": null,
        "StaffDateofBirth": "0000-00-00",
        "StaffMobileNo": "9717393656"
    }
}

**Comment by PM-Vallesoft** [comment]
> Staff Gender should not be null , DOB also should be proper @PM-Vallesoft { "Status": 2000, "Message": "Success", "StaffDetails": { "StaffInfoId": "16402", "Staffname": "Shikar Jain", "Staffcode": "TEMP01", "CenterName": "TEST CENTER 311", "CenterCode": "INDLTEST0", "StaffGender": null, "StaffDateofBirth": "0000-00-00", "StaffMobileNo": "9717393656" } }

New entries for new no's have been updated.
![image](https://user-images.githubusercontent.com/43747392/144985296-51737d18-0dfa-4c42-9316-f0d1c526580e.png)
