### ISSUE TITLE
Resend OTP API for Expert

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#53]
We need resend OTP API for expert.
I tried to reuse customers Resend OTP API but not getting authToken

{
    "Status": 2001,
    "Message": "Invalid OTP or OTP Expired.",
    "TokenInfo": {
        "auth_token": null,
        "deviceId": null,
        "expertName": null,
        "expertMobile": null,
        "expertEmail": null
    }
}

**Comment by PM-Vallesoft** [comment]
> We need resend OTP API for expert. I tried to reuse customers Resend OTP API but not getting authToken
> 
> { "Status": 2001, "Message": "Invalid OTP or OTP Expired.", "TokenInfo": { "auth_token": null, "deviceId": null, "expertName": null, "expertMobile": null, "expertEmail": null } }

Use Expert Login Signin API (to generate otp)
![image](https://user-images.githubusercontent.com/43747392/145163929-39ecd9f7-7c66-4ed6-b7ee-b0581c72b62f.png)
