### ISSUE TITLE
Change expert number

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#54]
Do we need change number option for Expert on OTP screen or not.
If needed then provide API otherwise we would remove it  @PM-Vallesoft 
![otp](https://user-images.githubusercontent.com/87964189/145192239-f7e0f93f-6f54-40b8-b9fd-ae7b65eb869d.jpeg)

**Comment by PM-Vallesoft** [comment]
> Do we need change number option for Expert on OTP screen or not. If needed then provide API otherwise we would remove it @PM-Vallesoft ![otp](https://user-images.githubusercontent.com/87964189/145192239-f7e0f93f-6f54-40b8-b9fd-ae7b65eb869d.jpeg)

NO
