### ISSUE TITLE
Expert Creds

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#55]
@PM-Vallesoft  Please add these numbers for Expert 
9475552277,   8448755213

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Please add these numbers for Expert 9475552277, 8448755213

Use the existing for Expert. Cannot create new users for expert even in Test Center. 
@SoniaManocha Pls takeover.

**Comment by rgnarok** [comment]
@kanishkavayuz use the numbers which are added already
