### ISSUE TITLE
Need More Appointments in the Expert Appointemnte list

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#56]
@PM-Vallesoft  Please add more appointment data in the appointment list
![image](https://user-images.githubusercontent.com/78138350/145394332-50f8fc2c-61fe-48b5-b472-3bcc7e4c9508.png)

**Comment by Shaktivayuz** [comment]
@PM-Vallesoft  
1.  need video appointments in the list.
2. Correct Appoimtment Doc URL
3. Provide proper date n start time

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft
> 
> 1. need video appointments in the list.
> 2. Correct Appoimtment Doc URL
> 3. Provide proper date n start time

@SoniaManocha pls give them more appointments from E-Diary.

**Comment by Shaktivayuz** [comment]
@SoniaManocha  plz add video appointment also ASAP

**Comment by SoniaManocha** [comment]
Hi Aakash, As discussed, as the services are not made live, It has to be done by back end only. Pls close n confirm.

**Comment by rgnarok** [comment]
@kanishkavayuz @Shaktivayuz  update?

**Comment by kanishkavayuz** [comment]
@rgnarok  no its not done

**Comment by Shaktivayuz** [comment]
@SoniaManocha  On which contact no you added appointments n consultation?

**Comment by SoniaManocha** [comment]
on my no - 09312782089

**Comment by Shaktivayuz** [comment]
@SoniaManocha  I checked at your contact no. You have added only one video consultation.
Again DateTime format is not proper.
Kindly make it correct , also add 2-3 appointments of future dates n 2-3 appointments of past dates so we can properly manage filters
<img width="922" alt="video" src="https://user-images.githubusercontent.com/87964189/146155758-5fe6b2e2-7ce1-4439-9107-fb8c88218d5d.png">

**Comment by SoniaManocha** [comment]
I have added appointment from App only...Aakash has to check why the date format is incorrect and get this resolved.

am adding 3-4c more appoints as per your request...

**Comment by PM-Vallesoft** [comment]
> 

@SoniaManocha as discussed,,,, I will provide expert video appointment b y tomorrow. Meanwhile @kanishkavayuz you implement the functionality. It's just the values that will change. Nothing is wrong in the API FYI......

**Comment by Shaktivayuz** [comment]
@SoniaManocha  On which contact no you added 3-4 Appointments n also 3-4 video consultation.

**Comment by Shaktivayuz** [comment]
Today I checked on staffname shikhar n contact no - 9717393656.
Document URL is correct but Date time format still wrong.  @PM-Vallesoft 
<img width="960" alt="video1" src="https://user-images.githubusercontent.com/87964189/146354038-20ed5d91-a909-48f5-931d-4aa1c631666f.png">

**Comment by PM-Vallesoft** [comment]
> Today I checked on staffname shikhar n contact no - 9717393656. Document URL is correct but Date time format still wrong. @PM-Vallesoft <img alt="video1" width="960" src="https://user-images.githubusercontent.com/87964189/146354038-20ed5d91-a909-48f5-931d-4aa1c631666f.png">

@kanishkavayuz @rohitrvayuz @Shaktivayuz 

I have given expert video appointments on 9312782089.
![image](https://user-images.githubusercontent.com/43747392/146538843-76655364-5f92-4eb9-bf15-a9713c5bdf82.png)

**Comment by rohitrvayuz** [comment]
@kanishkavayuz @Shaktivayuz  Please check and close

**Comment by Shaktivayuz** [comment]
Date format not correct also didn't get 3-4 appointments for future date n 3-4 appointments of previous date as required @rohitrvayuz

**Comment by PM-Vallesoft** [comment]
> Date format not correct also didn't get 3-4 appointments for future date n 3-4 appointments of previous date as required @rohitrvayuz

date format is yymmdd, how come not correct???? Also i gave 2 apts for future date.... Arenot the sufficient???

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  Please add at least  appointments to the list and with the correct date format, because we need to check with the date filter

**Comment by PM-Vallesoft** [comment]
I have given two assignments..... 

{
    "Status": 2000,
    "Message": "Success",
    "AppointmentexpertDetails": [
        {
            "AppointmentId": "84",
            "BookingId": "NA",
            "CenterName": "TEST CENTER 311",
            "CenterCode": "INDLTEST0",
            "ClientId": "CLMC/19/00000089879",
            "clientname": "Sonia Rani Manoch",
            "BookingNumber": "Other",
            "AppointmentDate": "2022-01-10",
            "AppointmentStartTime": "15:30:00",
            "AppointmentStartDateTime": 1641808800,
            "AppointmentEndTime": "16:00:00",
            "AppointmentEndDateTime": 1641810600,
            "AppointmentRemark": "Video testing ediary",
            "AppointmentAttDoc": "http://lms.vlccwellness.com/booking_boc/20211221014622_unnamed.png",
            "AppointmentStatus": "Booked",
            "AppointmentType": "Video Consultations",
            "AppointmentServiceexpertDtl": [
                {
                    "AppointmentServiceId": "591",
                    "ServiceName": "GenX Skin Facial Treatment",
                    "ServiceCode": "SRV0001865",
                    "Staffname": "Sonia Rani Manocha"
                }
            ]
        },
        {
            "AppointmentId": "85",
            "BookingId": "NA",
            "CenterName": "TEST CENTER 311",
            "CenterCode": "INDLTEST0",
            "ClientId": "CLMC/19/00000089879",
            "clientname": "Sonia Rani Manoch",
            "BookingNumber": "Other",
            "AppointmentDate": "2022-01-11",
            "AppointmentStartTime": "15:30:00",
            "AppointmentStartDateTime": 1641895200,
            "AppointmentEndTime": "16:30:00",
            "AppointmentEndDateTime": 1641898800,
            "AppointmentRemark": "Video testing ediary",
            "AppointmentAttDoc": "http://lms.vlccwellness.com/booking_boc/20211221031331_unnamed.png",
            "AppointmentStatus": "Booked",
            "AppointmentType": "Video Consultations",
            "AppointmentServiceexpertDtl": [
                {
                    "AppointmentServiceId": "595",
                    "ServiceName": "2X Whitening Glow Facial Treatment Blanc Precision ",
                    "ServiceCode": "SRV0001640",
                    "Staffname": "Sonia Rani Manocha"
                }
            ]
        }
    ]
}

@SoniaManocha i have given two sample. please give rest more required..

**Comment by Shaktivayuz** [comment]
Plz check appointment Listing API , it is not working properly today after 2:00 PM. yesterday you added 8 appointment and 2 consultation on Sonia number - 93127 82089.
Always giving invalid token  @PM-Vallesoft 
<img width="960" alt="sonia" src="https://user-images.githubusercontent.com/87964189/147084429-c8330e2c-2c60-43c6-a6a6-8e3295cf0230.png">

**Comment by PM-Vallesoft** [comment]
> Plz check appointment Listing API , it is not working properly today after 2:00 PM. yesterday you added 8 appointment and 2 consultation on Sonia number - 93127 82089. Always giving invalid token @PM-Vallesoft <img alt="sonia" width="960" src="https://user-images.githubusercontent.com/87964189/147084429-c8330e2c-2c60-43c6-a6a6-8e3295cf0230.png">

pls check again. Net connectivity might be the issue.
