### ISSUE TITLE
Login API 

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#57]
We need employeID at the login time , otherwise we are unable to get employee ID for Appointment Listing unless we hit Profile API @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> We need employeID at the login time , otherwise we are unable to get employee ID for Appointment Listing unless we hit Profile API @PM-Vallesoft

use profile api instead. what is the use of sending same data across multiple api's and use of giving different api's?

**Comment by Shaktivayuz** [comment]
But we need to hit 3 API at login time it affects performance of the app @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> But we need to hit 3 API at login time it affects performance of the app @PM-Vallesoft

As discussed with @rgnarok in meeting, I suggested same but due to security concerns he recommended to provide separate Profile API for it.
