### ISSUE TITLE
Need update in the Video Consultation Token Update API

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#58]
![image](https://user-images.githubusercontent.com/78138350/145567302-abfe35a5-c56c-49dd-9f4a-63ae919d20bd.png)
@PM-Vallesoft  There's a need for an update  in the  Video Consultation Token Update API, as of now, the customer/Patient can update the token, But as per the Flow in Video Consultation the doctor should update the token so that the patient can get the updated token and can interact, so we need the following  change in the API,
 1. Client mobile should be replaced with expert mobile 
 2. the auth token and device_id should be validated with an expert database

**Comment by PM-Vallesoft** [comment]
> ![image](https://user-images.githubusercontent.com/78138350/145567302-abfe35a5-c56c-49dd-9f4a-63ae919d20bd.png) @PM-Vallesoft There's a need for an update in the Video Consultation Token Update API, as of now, the customer/Patient can update the token, But as per the Flow in Video Consultation the doctor should update the token so that the patient can get the updated token and can interact, so we need the following change in the API,
> 
> 1. Client mobile should be replaced with expert mobile
> 2. the auth token and device_id should be validated with an expert database

@PankajBhutani @SoniaManocha @rgnarok @ShikharVayuz  As per discussion in the meeting It was suggested by Shikhar. How come @kanishkavayuz it's happening that since you have started taking HOLD of the the things We are daily changing API's????

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  Since we had no clarity on the Expert Video Consultaion Flow, so we need this change

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Since we had no clarity on the Expert Video Consultaion Flow, so we need this change

@Shaktivayuz Since we have discussed this issue in the meeting and already have clarity, Close this if we are on same page.
@rgnarok @PankajBhutani @kanishkavayuz

**Comment by PM-Vallesoft** [comment]
@rgnarok @kanishkavayuz @PankajBhutani 
New API sent via mail........
Video Consultation Token Update RBS(By Expert)-
Since currently No video appointment is a part of Package as of now...... Will provide for package as well later since it will take much longer. But currently video services are for rbs only so you can go ahead with that provided now......

expert end-----
![image](https://user-images.githubusercontent.com/43747392/146174140-d4f8b38c-75d5-4242-91e5-249b66904b85.png)

Client end-----
![image](https://user-images.githubusercontent.com/43747392/146174325-40ff26c2-9e4a-405a-a703-3004ecfdc4ed.png)

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  ok well check it

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  im not able to update the Token and im getting this response is this when i try to do it
this is from customer end, im testing EnableX  
this is from client end appointment ID
![image](https://user-images.githubusercontent.com/78138350/147541065-b5d8eeca-a094-4f05-94c0-7359569850a0.png)

![image](https://user-images.githubusercontent.com/78138350/147541098-058edad2-f782-46f5-8ba5-7a8bb5f4557f.png)

this is from client end ExpertID

![image](https://user-images.githubusercontent.com/78138350/147544004-696f8be1-c49b-4cde-be91-e685378c36f7.png)

![image](https://user-images.githubusercontent.com/78138350/147544026-20b76a34-4742-4e14-bb6b-4094fe271653.png)

**Comment by PM-Vallesoft** [comment]
It was already discussed that you need the token updation from expert end and not the client end....

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  ok checking with new appointment from the expert side
