### ISSUE TITLE
OTP Screen is throwing error when we run it on local 

### ISSUE THREAD

**Issue by ibsingh13** [VAYUZ-VLCC/vlcc-api-issues#60]
[Error message.docx](https://github.com/VAYUZ-VLCC/vlcc-api-issues/files/7708858/Error.message.docx)

**Comment by rgnarok** [comment]
@kanishkavayuz

**Comment by kanishkavayuz** [comment]
@rgnarok  its app related issue

**Comment by rgnarok** [comment]
@Shaktivayuz  @rohitrvayuz  please do the needful

**Comment by kanishkavayuz** [comment]
@Shaktivayuz  Please check this issue

**Comment by rohitrvayuz** [comment]
1. git fetch origin
2. git checkout expert

**Comment by rgnarok** [comment]
@rohitrvayuz  has a word with Indra its is an issue of running the code on local machine
