### ISSUE TITLE
Call Details

### ISSUE THREAD

**Issue by rohitrvayuz** [VAYUZ-VLCC/vlcc-api-issues#61]
> You can get the session usage data of your room via rest API call as shown below:
> 
> GET https://api.enablex.io/video/v1/cdr/room/{{$ROOM_ID}}
> Authorization: Basic XXXXXXX
> Alternatively, you can download the summary of your session CDR from the Portal Dashboard.
> 
> Read more about Video API Call Detail Report (CDR).

**Comment by PM-Vallesoft** [comment]
> > You can get the session usage data of your room via rest API call as shown below:
> > GET [https://api.enablex.io/video/v1/cdr/room/{{$ROOM_ID}}](https://api.enablex.io/video/v1/cdr/room/%7B%7B$ROOM_ID%7D%7D)
> > Authorization: Basic XXXXXXX
> > Alternatively, you can download the summary of your session CDR from the Portal Dashboard.
> > Read more about Video API Call Detail Report (CDR).

@rohitrvayuz So will this data be forever, like at anytime if we pass Roomid in it, data will be there or do wee need to download it on our server???

**Comment by rohitrvayuz** [comment]
> > > You can get the session usage data of your room via rest API call as shown below:
> > > GET [https://api.enablex.io/video/v1/cdr/room/{{$ROOM_ID}}](https://api.enablex.io/video/v1/cdr/room/%7B%7B$ROOM_ID%7D%7D)
> > > Authorization: Basic XXXXXXX
> > > Alternatively, you can download the summary of your session CDR from the Portal Dashboard.
> > > Read more about Video API Call Detail Report (CDR).
> 
> @rohitrvayuz So will this data be forever, like at anytime if we pass Roomid in it, data will be there or do wee need to download it on our server??? Since you are generating roomid, i will provide you key in appointment listing API so that against each appointment that key is optional. if you pass video detail URL it will be saved else not.

@PM-Vallesoft  I am not sure about it. Will have to check with EnableX.
