### ISSUE TITLE
Expert Notification API

### ISSUE THREAD

**Issue by Shaktivayuz** [VAYUZ-VLCC/vlcc-api-issues#62]
Plz provide Notification API for Expert App @PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> Plz provide Notification API for Expert App @PM-Vallesoft

As already Discussed ,  I need expert app to test and hit notifications......

**Comment by Shaktivayuz** [comment]
https://drive.google.com/file/d/1AfCmVY_Ed0ncDrrzMyDBQNG_jBbbxjnB/view?usp=sharing 
plz Signin as expert, if you logout then you need to signin gain @PM-Vallesoft

**Comment by Shaktivayuz** [comment]
https://drive.google.com/file/d/1xju17OI1kLhB4OmB4F4DzjeF8-yn3hUN/view?usp=sharing
Plz, Signin as an expert ,if you kill app then you need to login again
@PM-Vallesoft

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  any Updates?

**Comment by PM-Vallesoft** [comment]
Sent..
check mail

@rgnarok @PankajBhutani @rohitrvayuz @kanishkavayuz @ShikharVayuz @Shaktivayuz

**Comment by PM-Vallesoft** [comment]
![image](https://user-images.githubusercontent.com/43747392/147247717-a3b08735-b3ac-4126-89f1-6acbcb2b7aea.png)
![image](https://user-images.githubusercontent.com/43747392/147247737-16fd08b2-3caf-4849-8111-c36e3562851c.png)

**Comment by Shaktivayuz** [comment]
ok

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  Expert Notification list has same URL, with Similar body (device_id, auth_token), but body differs with client_mobile (Customer) and staff_mobile(Expert), but we are getting invalid token as following below
 
![image](https://user-images.githubusercontent.com/78138350/147327166-e933ad06-8abe-4129-9af6-d900ee11e633.png)

Please check with this no "8951900164"

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Expert Notification list has same URL, with Similar body (device_id, auth_token), but body differs with client_mobile (Customer) and staff_mobile(Expert), but we are getting invalid token as following below
> 
> ![image](https://user-images.githubusercontent.com/78138350/147327166-e933ad06-8abe-4129-9af6-d900ee11e633.png)
> 
> Please check with this no "8951900164"
> 
> @rgnarok @rohitrvayuz

Have you checked my 1st screenshot above and the URl in it ????

for expert it's- https://www.lms.vlccwellness.com/api/api_notification_expert_list.php?request=notification_list

**Comment by kanishkavayuz** [comment]
ok

**Comment by kanishkavayuz** [comment]
@
