### ISSUE TITLE
Pay U

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#64]
Need Sanbox details

**Comment by kanishkavayuz** [comment]
@PankajBhutani  @SoniaManocha  @PM-Vallesoft  Any Updates?.

**Comment by kanishkavayuz** [comment]
Recieved in the Email

**Comment by kanishkavayuz** [comment]
@PM-Vallesoft  @SoniaManocha  We are facing some issues in integrating PayU, we need support from PayU we need to raise the ticket for the same, The URL, and the Creds that you have Shared over the mail and are not working, so Please Provide the Right Creds.

**Comment by kanishkavayuz** [comment]
@SoniaManocha  @PM-Vallesoft  any update.

**Comment by PankajBhutani** [comment]
Please update error here...!

**Comment by kanishkavayuz** [comment]
@PankajBhutani  
this is payment initiation page 
![image](https://user-images.githubusercontent.com/78138350/147473683-ae6b4882-8781-46b7-aee7-857d1fcb0c6f.png)
im trying  to cancel /fail the transaction
![image](https://user-images.githubusercontent.com/78138350/147473794-d06d9494-fad4-450a-893b-128c2738167c.png)
![image](https://user-images.githubusercontent.com/78138350/147473808-68e6b057-47ab-4dd0-a5ba-67d7d2f23662.png)

As we are Sending the furl and surl  and while making payment inintiation , after redirecting cooresponding and succes and the dailure of the payment transaction 
![image](https://user-images.githubusercontent.com/78138350/147475131-326483a1-cd50-4490-b5c3-11286351a32a.png)
  
this is the issue,  which we are facing in the payment redirection
![image](https://user-images.githubusercontent.com/78138350/147474598-dd607b0b-59c7-42c8-a8de-79bd3161f613.png)

@PankajBhutani
