### ISSUE TITLE
Center's City name Issue

### ISSUE THREAD

**Issue by kanishkavayuz** [VAYUZ-VLCC/vlcc-api-issues#66]
@PM-Vallesoft, as we are trying to sort the centers by users current location and there is a spelling mismatch  of city names with  respect to the GCP provided city names, Please loook in to this issue
![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/78138350/147437345-dd3a168c-e974-40d5-bf71-36503c6eb374.png)

@rgnarok @rohitrvayuz

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft, as we are trying to sort the centers by users current location and there is a spelling mismatch of city names with respect to the GCP provided city names, Please loook in to this issue ![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/78138350/147437345-dd3a168c-e974-40d5-bf71-36503c6eb374.png)
> 
> @rgnarok @rohitrvayuz

@SoniaManocha pls check center master at your end.

**Comment by SoniaManocha** [comment]
Hi Kanishk,...As just discussed, Kindly confirm and share the list of City names as available in GCP. Will get this updated in LMS accordingly.

**Comment by kanishkavayuz** [comment]
@SoniaManocha  I need to check on the same, we need to  discuss on  the Call

**Comment by SoniaManocha** [comment]
City names have been updated in LMS as shared by Kush.

**Comment by kanishkavayuz** [comment]
ok well check

**Comment by kanishkavayuz** [comment]
Updated Cities  are Updated in the Centers List
