### ISSUE TITLE
Appointment listing / Video consultation 

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#69]
Same appointment  / video consultation is coming in the listing for all the numbers

**Comment by rohitrvayuz** [comment]
@PM-Vallesoft This was coming correct until yesterday. Please check and confirm.

**Comment by rohitrvayuz** [comment]
@PM-Vallesoft

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft

Pls share the same cases. I am unable to understand the issue.

**Comment by rohitrvayuz** [comment]
Earlier all users were getting the same appointments. But it is working now.
