### ISSUE TITLE
Addition of packages to the given mobile numbers.

### ISSUE THREAD

**Issue by ShikharVayuz** [VAYUZ-VLCC/vlcc-api-issues#8]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>List of Auth and
mobile no</p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

<div style='direction:ltr'>

Auth | Mobile number | Device id | Name
-- | -- | -- | --
0d4bbd24bccbd688aac0b1cef056a412a7833fea36dfdac85bd7daffe3b78943 | 9599204583 | c15c10fc9aa65615 | Rohit
6b452ef591e0c2fc2c7bbcd9a937c314e1d8a4819aef4196e5350ed23e76e673 | 7206647813 | c15c10fc9aa65615 | Ankit
0c75f6b0d41d54ee7684cba22cac3350132a4223d6833c11c6c45cc83da8367b | 8287371867 | c15c10fc9aa65615 | Shakti
dcee5c439c337008a9e7011888874c4f5f606bc2035cd6c0c600e5c137f5fc5a | 9717393656 | c15c10fc9aa65615 | Shikhar Jain

</div>

</body>

</html>

![image](https://user-images.githubusercontent.com/86296418/138024540-a8937759-6510-466f-8c09-621f4953755a.png)

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Add the packages with expiry after the current date else logic flow will not be working right

ok

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Add the packages with expiry after the current date else logic flow will not be working right

updated.

![image](https://user-images.githubusercontent.com/43747392/139627937-bb80cc82-c453-4613-a802-377d51380aa7.png)
