### ISSUE TITLE
Category >> Service listing

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#80]
Cost of each service is not coming up on the listing please add correct cost right now it is showcasing P instead of the cost

**Comment by rohitrvayuz** [comment]
@PM-Vallesoft Please update when this is done from your end.

**Comment by PM-Vallesoft** [comment]
> @PM-Vallesoft Please update when this is done from your end.

@SoniaManocha FYI

**Comment by SoniaManocha** [comment]
Pls share sample cases to check the issue....

**Comment by rohitrvayuz** [comment]
![Screenshot_1641288221](https://user-images.githubusercontent.com/78350161/148037379-178970b8-4fe0-4bad-9de3-db53b43ab22f.png)
@SoniaManocha

**Comment by rohitrvayuz** [comment]
remove cost for categories and services for general
