### ISSUE TITLE
Cancelled appointment / video consultation

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#99]
I have cancelled the appointment the toast came but it is not same as what we have for the reschedules it must give me some time to undo cancellation too lease fix and the toast
Also on the header it is still showcasing booked make it cancel is cancellation is done

**Comment by rohitrvayuz** [comment]
Once cancelled then the appointment can't be rescheduled.
It shows a warning on the pop-up too

**Comment by rohitrvayuz** [comment]
Rest issues fixed
